### ISSUE TITLE
Set Display Name not as the username

### ISSUE THREAD

**Issue by ShlomiPorush** [NodeBB/nodebb-plugin-sso-oauth2-multiple#27]
Hi. Love this plugins - i was able to set SSO without any issue.
Just one thing, can i set the display name "Full Name" via SSO? 

![image](https://github.com/NodeBB/nodebb-plugin-sso-oauth2-multiple/assets/5992161/e5d8adf5-8366-412d-afa7-25727f0c9fea)

**Comment by julianlam** [comment]
Hi @ShlomiPorush — currently there is no support for it in the plugin.

However, I do think that it is something we can add, since it is defined in the OpenID Connect specification, and we could use both `preferred_username` and `name` for the username and full name respectively.

**Comment by julianlam** [comment]
@ShlomiPorush Yes, that's right, the spec has multiple values for a username-like item, so I grab all three if present (since not all providers send all values) and just use whatever I can.

I should be straightforward to add in support for full name.

**Comment by ShlomiPorush** [comment]
I guessed that was really the reason.

Although it is less relevant for me - I use authentik so, i can change any value sent over.

For example:
```
    "email": "email@domain.com",
    "email_verified": true,
    "name": "Display Name",
    "given_name": "Display Name",
    "preferred_username": "user",
    "nickname": "user",
    "roles": [
        "admin",
```

Anyway. Looking forward to the update

**Comment by julianlam** [comment]
Please try v1.4.0 of the plugin. Note that you will have to toggle the appropriate "Adjustment":

![image](https://github.com/NodeBB/nodebb-plugin-sso-oauth2-multiple/assets/923011/6d14c74f-d319-4fef-a261-f73251f203df)
