### ISSUE TITLE
Plugin seems to not work

### ISSUE THREAD

**Issue by dominikx96** [NodeBB/nodebb-plugin-sso-oauth2-multiple#48]
I installed the plugin using npm, I rebuilt the app and commited, pushed to heroku.
I restarted and rebuilded the app on the server and I see the plugin, but when I am trying to open plugin page, I am getting:

Internal server error.
Failed to lookup view! Did you run `./nodebb build`?

Fresh NodeBB install, NodeBB v3.7.4

**Comment by julianlam** [comment]
Hi, this looks to be a Heroku issue, which I do not know how to debug.

Please make sure that when building the NodeBB assets, those directories get pushed to Heroku as well.
