### ISSUE TITLE
Feature Request: Link Existing Non-OAuth Accounts to Third-Party OAuth Providers

### ISSUE THREAD

**Issue by moemoequte** [NodeBB/nodebb-plugin-sso-oauth2-multiple#52]
Hello,

I am currently using the nodebb-plugin-sso-oauth2-multiple and it works great for its intended purpose. However, I've encountered a limitation that affects user flexibility. Users who originally registered without using OAuth are currently unable to link their existing NodeBB accounts to third-party OAuth providers.

This feature would be incredibly useful for allowing all users to consolidate their logins and enhance account security by integrating with external OAuth providers.

Could this functionality be considered for a future update? It would greatly enhance user experience by providing more versatility in account management.

Thank you for considering this request!

**Comment by julianlam** [comment]
Hi @moemoequte, the plugin currently has the capability of automatically associating with an existing local account **if an email match is found**.

However, that email must be validated (either via confirmation link sent to email, or via admin confirmation in ACP).

Once validated, as long as the OAuth provider supplies the email in the profile data, then NodeBB will attempt to find a match.

Hope that helps!
